apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-server
    namespace: test
    labels:
        app: nginx-server
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nginx-server
    template:
        metadata:
            labels:
                app: nginx-server
        spec:
            containers:
                - name: nginx-server
                  image: test_new
                  ports:
                    - containerPort: 8080
