apiVersion: v1
kind: Service 
metadata:
  name: server-service
  namespace: app-space
spec: 
  type: LoadBalancer
  selector:
    app: server 
  ports:
    - port: 8181
      name: http
      targetPort: 8181
      
