apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
    namespace: app-space
    labels:
        app: server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: server
                  image: ttl.sh/app-3118838@sha256:b81a8b443de74c6da649b0267638f3121ba82ba6b9f22e59b0d1b51aaf8ca2b2
                  ports:
                    - containerPort: 8181
