apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
    namespace: app-space
    labels:
        app: server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: server
                  image: ttl.sh/app-3397406@sha256:47e6f1c10d3077865af351f0062e3588e11c7e5680066b097b0761e0dc2ab133
                  ports:
                    - containerPort: 8181
