apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
    namespace: app-space
    labels:
        app: server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: server
                  image: ttl.sh/app-5604645@sha256:f1269ede93ea41e59f4bd73eff3c59632b4474eab20c91b68099c60eb594a5e8
                  ports:
                    - containerPort: 8181
