kind: Service 
apiVersion: v1 
metadata:
  name: server-service 
spec: 
  type: NodePort
  selector:
    app: server 
  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - nodePort: 30163
      port: 8383 
      targetPort: 8181
