# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: App:branch

on:
  push:
    branches-ignore:
      - main
    paths:
      - App/**
      - .github/workflows/branch_app.yml 
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: golang setup 
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: mage test
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: testApp
          workdir: ./CI/builder
      
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: golang setup 
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: mage build
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: buildApp
          workdir: ./CI/builder
         
