# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build CI

on:
  push:
    branches: [ "main" ]
    paths:
      - CI/
      - .github/workflows/build_ci.yml
  pull_request:
    branches: [ "main" ]

jobs:
  build_CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Build builder
      run: cd CI/builder && go build
    - name: Build trigger
      run: cd CI/trigger && go build  
  #build:
  #  runs-on: ubuntu-latest
  #  needs: [test]
  #  steps:
  #    - name: Set up QEMU
  #      uses: docker/setup-qemu-action@v3
  #    - name: Set up Docker Buildx
  #      uses: docker/setup-buildx-action@v3
  #    - name: Login to Docker Hub
  #      uses: docker/login-action@v3
  #      with:
  #        username: ${{ secrets.DOCKERHUB_USERNAME }}
  #        password: ${{ secrets.DOCKERHUB_TOKEN }}
  #    - name: Build and push
  #      uses: docker/build-push-action@v5
  #      with:
  #        push: true
  #        file: ./CI/Dockerfile
  #        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mean-mug-ci:latest
         
