# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build CI

on:
  push:
    branches: [ "main" ]
    paths:
      - CI/builder/*.*
      - CI/trigger/*.*
      - .github/workflows/build_ci.yml

  pull_request:
    branches: [ "main" ]

jobs:
  build_CI:
    runs-on: ubuntu-latest
    permissions: write-all  
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'
    - name: install dagger cli 
      run: |
        cd /usr/local
        curl -L https://dl.dagger.io/dagger/install.sh | sh 
    - name: run dagger
      run: cd CI/builder && dagger run go run main.go
    - uses: stefanzweifel/git-auto-commit-action@v5        
  #build:
  #  runs-on: ubuntu-latest
  #  needs: [test]
  #  steps:
  #    - name: Set up QEMU
  #      uses: docker/setup-qemu-action@v3
  #    - name: Set up Docker Buildx
  #      uses: docker/setup-buildx-action@v3
  #    - name: Login to Docker Hub
  #      uses: docker/login-action@v3
  #      with:
  #        username: ${{ secrets.DOCKERHUB_USERNAME }}
  #        password: ${{ secrets.DOCKERHUB_TOKEN }}
  #    - name: Build and push
  #      uses: docker/build-push-action@v5
  #      with:
  #        push: true
  #        file: ./CI/Dockerfile
  #        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mean-mug-ci:latest
         
