# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: App:main

on:
  push:
    branches: 
     - main
    paths:
      - App/**
      - .github/workflows/main_app.yml
      - CI/**
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: golang setup 
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: mage test
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: ci
          workdir: ./CI/builder      
  Deploy:
    runs-on: ubuntu-latest
    needs: [CI]
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: golang setup 
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: mage deploy
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: cd ${{ github.token }}
          workdir: ./CI/builder    
