# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: App:main

on:
  push:
    branches: 
     - main
    paths:
      - App/**
      - .github/workflows/main_app.yml
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: golang setup 
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: mage test
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: testApp
          workdir: ./CI/builder      
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: golang setup 
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: mage build
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: buildApp
          workdir: ./CI/builder
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: golang setup 
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: mage deploy
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: deployApp ArgoCD/deployment.yml ${{ github.repository }} ${{ GITHUB_TOKEN }}
          workdir: ./CI/builder    
